---
tags:
  - Rust
---

# 错误处理

Rust 将错误分为两大类：**可恢复的**（*recoverable*）和 **不可恢复的**（*unrecoverable*）错误。对于一个可恢复的错误，比如文件未找到的错误，我们很可能只想向用户报告问题并重试操作。不可恢复的错误总是 bug 出现的征兆，比如试图访问一个超过数组末端的位置，因此我们要立即停止程序。

## 处理不可恢复错误

当代码出现了你束手无策的错误时，可以通过调用 `panic!` 来终止程序的运行。在实践中有两种方法造成恐慌：
- 执行会造成恐慌的操作，例如数组访问越界、字符串无效索引等。
- 显式调用 `panci!` 宏。

通常情况下这些 `panic` 会打印一个错误信息，并清理栈数据然后退出。

> [!note] 终止与展开
> 默认情况下，当出现 `panic` 时程序会开始 **展开**（*unwinding*），这意味着 Rust 会回溯栈并清理它遇到的每一个函数的数据，不过这个回溯并清理的过程有很多工作。
>
> 或者你可以在 `Cargo.toml` 中的 `[profile]` 部分增加 `panic = 'abort'`，可以在出现 `panic` 时直接终止程序运行。

> [!note] 打印调用栈
> 将环境变量 `RUST_BACKTRACE` 设置为任何不为 0 的值，可以在 Rust 出现 `panic` 时打印调用栈信息。
>
> 为了查看调用栈信息，除了通过环境变量启用 `backtrace` 外，还需要启用调试符号 (debug symbols)。默认情况下，当不使用 `--release` 编译时会启用调试符号。

## 处理可恢复错误

大部分错误并没有严重到需要程序完全停止执行。有时函数失败的原因很容易理解并加以处理。Rust 中提供了一个 `Result` 枚举用于处理潜在的错误，其定义如下：
```rust
enum Result<T, E> {
	Ok(T),
	Err(E),
}
```

其中 `T,E` 为泛型参数，其中 `T` 表示成功时返回的变体 `Ok` 中的数据类型，`E` 表示失败时返回的变体 `Err` 中的错误的类型。

当我们调用一个返回值为 `Result` 的函数时，意味着该函数可能成功也可能失败，使用 `match` 语句可以保证我们处理了所有的可能的情况。

```rust
use std::fs::File;

fn main() {
    let greeting_file_result = File::open("hello.txt");

    let greeting_file = match greeting_file_result {
        Ok(file) => file,
        Err(error) => panic!("Problem opening the file: {error:?}"),
    };
}
```

> [!note] 与 `Option` 枚举一样，`Result` 枚举也包含在 prelude 中，可以直接使用 `Err` 与 `Ok`。

### 匹配不同的错误

前面的例子中，不论发生什么错误都会产生 `panic`，我们一般希望对不同的错误产生不同的处理。我们可以通过在内部再添加 `match` 语句来匹配不同的错误类型。

```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let greeting_file_result = File::open("hello.txt");

    let greeting_file = match greeting_file_result {
        Ok(file) => file,
        Err(error) => match error.kind() {
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("Problem creating the file: {e:?}"),
            },
            _ => {
                panic!("Problem opening the file: {error:?}");
            }
        },
    };
}
```

> [!note] `Err::kind()` 方法返回一个 `ErrorKind` 类型的枚举，包含了各种错误的类型。

> [!info] `match` 的替代方案
> 多层的 `match` 嵌套容易导致代码难以理解。使用 [[Rust/闭包|闭包]] 可以简化这种处理过程。
> ```rust
> use std::fs::File;
> use std::io::ErrorKind;
> 
> fn main() {
>     let greeting_file = File::open("hello.txt").unwrap_or_else(|error| {
>         if error.kind() == ErrorKind::NotFound {
>             File::create("hello.txt").unwrap_or_else(|error| {
>                 panic!("Problem creating the file: {error:?}");
>             })
>         } else {
>             panic!("Problem opening the file: {error:?}");
>         }
>     });
> }
> ```

### `unwarp` 与 `expect`

`match` 能够胜任它的工作，不过它可能有点冗长并且不总是能很好的表明其意图。`Result<T, E>` 类型定义了很多辅助方法来处理各种更为特定的任务。
- `unwrap` 方法是一个快捷方式，如果 `Result` 中的变体是 `Ok`，那么 `unwrap` 会为我们返回其中的值。如果其中的变体是 `Err`，那么 `unwrap` 会帮助我们调用 `panic!`。
- `except` 方法与 `unwrap` 方法作用相同，但是 `except` 允许我们自定义 `panic!` 输出的错误信息。

> [!note] 在生产环节中，大部分的人都会使用 `except` 方法来提供更加有效的信息。

> [!example]-
> ```rust
> use std::fs::File;
> 
> fn main() {
> let greeting_file = File::open("hello.txt").unwrap();
> let greeting_file = File::open("hello.txt")
> 	.expect("hello.txt should be included in this project");
> }
> ```

### 传播错误

当函数中调用了可能会错误的操作时，除了在这个函数中处理错误外，还可以将这个错误返回给其调用者。这称为**传播**(*propagating*) 错误，可以更好的控制代码调用，因为比起这个函数，函数的调用者拥有更多的上下文信息，可以更好的处理错误。

下面是一个传播错误的例子：
```rust
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let username_file_result = File::open("hello.txt");

    let mut username_file = match username_file_result {
        Ok(file) => file,
        Err(e) => return Err(e),
    };

    let mut username = String::new();

    match username_file.read_to_string(&mut username) {
        Ok(_) => Ok(username),
        Err(e) => Err(e),
    }
}
```
我们通过在遇到错误时，提前终止函数，并直接将错误返回来实现传播错误。

传播错误非常常见，以至于 Rust 提供了一个 `?` 运算符来简化这一过程。下面的代码与上面的代码等价。
```rust
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let mut username_file = File::open("hello.txt")?;
    let mut username = String::new();
    username_file.read_to_string(&mut username)?;
    Ok(username)
}
```

这里 `?` 运算符所做的工作与前面的 `match` 相同，当 `Result` 枚举的变体为 `Ok` 时，取出其中的值作为表达式的结果；当 `Result` 枚举当变体为 `Err` 时，直接使用 `return` 语句使函数返回错误。

`?` 运算符还可以链式调用，它的优先级高于 `.` 运算符。因此，上面的代码还可以简化。
```rust
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let mut username = String::new();

    File::open("hello.txt")?.read_to_string(&mut username)?;

    Ok(username)
}
```

> [!note] `match` 与 `?` 的区别
> `match` 方法与 `?` 的实现上有一点不同，`?` 不是直接返回得到的错误，而是将返回的错误先传递给 `from` 方法，将其转换为与函数声明相同的错误类型之后，再进行返回。
>
> 对于实现了 `From trait` 的错误类型，这样的自动处理可以节省很多重复工作。当使用 `?` 返回了一个与函数声明不兼容的错误类型，且没有实现对应的 `From trait` 时，编译器会报错。
>

> [!note] `?` 用于 `Option`
> 与 `Result` 的使用方式相同，`?` 也可以用于返回值为 `Option` 的函数。
> - 如果值是 `None`，那么提前调用 `return` 返回 `None`。
> - 如果值是 `Some`，则取出其中的值作为表达式的结果。
>
> 你虽然可以将 `?` 用于输出为 `Option` 或者 `Result` 的函数，但是不能混搭它们。`?` 无法将一个 `Option` 转换为 `Result`，反之亦然。
>
> 实际上，`?` 可以用于任何返回值实现了 `FromResidual trait` 的函数中。

> [!note] 在 `main` 函数中使用 `?`
> `main` 函数无法直接使用 `?` 运算符，因为它的返回值不支持。但是 Rust 中允许我们将 `main` 函数的返回值设置为 `Result<(), Box<dyn Error>>`，并通过 `?` 来提前结束程序并返回不同的错误码。

## 选择 panic 还是 Result

`panic!` 与 `Result` 适用于不同的场景，它们的含义是不同的。
- **`panic!`** 适用于非预期的、不可恢复的错误状态，代表程序遇到了不应发生的严重问题。选择 `panic!` 可能意味着代替调用者做出了该错误不可恢复的决定。
	- 在编写示例、原型代码或测试时，使用可能导致 `panic!` 的方法（如 `unwrap` 或 `expect`）可以使代码更加简洁明了，避免复杂的错误处理逻辑干扰核心概念展示。
	- 当开发者明确知道某个操作不会失败（尽管编译器无法确认这一点），可以合理地使用 `unwrap` 或 `expect`，但最好使用 `expect` 并附上说明，解释为何认为该操作不可能失败。
	- 例如，一些不可能出现的情况，可以使用 `unwrap` 或者 `expect`。
- **`Result`** 提供了一种灵活的方式，允许调用者根据具体情况自行决定如何处理成功或失败的情况，增加了代码的可复用性和健壮性。
	- 当错误是可以预见的，并且可能需要不同的处理方式时，返回 `Result` 是更优的选择。

---
< [[Rust/常见集合|常见集合]] | [[Rust/泛型、Trait与生命周期|泛型、Trait与生命周期]] >
